name: dotnet build and test

on: [push]

jobs:
    build:
        env:
            ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        runs-on: ubuntu-latest
        steps:
            - name: Setup .NET SDK 6
              uses: actions/setup-dotnet@v1.7.2
              with:
                  dotnet-version: "6"
            - name: Setup .NET SDK 7
              uses: actions/setup-dotnet@v1.7.2
              with:
                  dotnet-version: "7"
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Test
              run: dotnet test --no-restore --verbosity normal --configuration Release --logger GitHubActions
