name: Tests

on:
  push:
    branches-ignore:
      - "master"
      - "dependabot/**"
    tags-ignore:
      - "**"

jobs:
  build:
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Setup .NET SDK 9.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"
      - uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --configuration Release --logger GitHubActions
