name: Dependabot PR

on: pull_request_target

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup .NET SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: Setup .NET SDK 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --configuration Release --logger GitHubActions
