name: Upload dotnet package

on:
    push:
        tags:
            - "*"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "8.0.x" # SDK Version to use.
            - name: Create the package
              run: dotnet pack --configuration Release OneBlink.SDK
            - name: Publish the package to Nuget
              run: dotnet nuget push OneBlink.SDK/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
