name: Nuget Publish

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # SDK Version to use.
      - name: Create the package
        run: dotnet pack --configuration Release OneBlink.SDK
      - name: Publish the package to Nuget
        run: dotnet nuget push OneBlink.SDK/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
